### ISSUE TITLE
TypeError cases

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly#140]
- [ ] https://twitter.com/python_tip/status/1349035347833978888  About positional only function arguments.
- [ ] TypeError: vars() argument must have `__dict__` attribute, when using an object with `__slots__`
- [ ] TypeError: 'in <string>' requires string as left operand, not int  (issue #148)
- [ ] TypeError: keywords must be strings (issue #165)
- [ ] TypeError: there are no type variables left ... (issue #184)
- [ ] TypeError: 'builtin_function_or_method' object is not subscriptable  (issue #166)
- [ ] TypeError: globals() takes no arguments (1 given) (issue #166)
- [ ] TypeError: string indices must be integers (note: might change wording in 3.10; see https://bugs.python.org/issue35077)

**Comment by aroberge** [comment]
```
Traceback (most recent call last):
  File "<friendly-console:2>", line 1, in <module>
    divmod(3, 0j)
TypeError: can't take floor or mod of complex number.

>>> 3 % 0j

Traceback (most recent call last):
  File "<friendly-console:3>", line 1, in <module>
    3 % 0j
TypeError: can't mod complex numbers.
```

**Comment by aroberge** [comment]
From issue #148 
```python
if 1 in "123":
    print()
```

**Comment by aroberge** [comment]
From issue #165 
```python
>>> d = {1: 'foo'}
>>> dict(**d)

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    dict(**d)                                                                                                                                                      
TypeError: keywords must be strings
```

**Comment by aroberge** [comment]
From issue #166 
```python
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = 1
>>> globals['x']

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    globals['x']                                                                                                                                                   
TypeError: 'builtin_function_or_method' object is not subscriptable                                                                                                

Did you mean globals('x')?                                                                                                                                          
>>> globals('x')

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:3>", line 1, in <module>                                                                                                                 
    globals('x')                                                                                                                                                   
TypeError: globals() takes no arguments (1 given)
```

**Comment by aroberge** [comment]
Issue migrated to new project.
